name: API and Component Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test API and Components
    strategy:
      matrix:
        node-version: [18.16.1, 20.4.0]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Start Containers
        run: |
          cp .env.template .env.test
          docker pull arangodb:latest
          docker compose up -d --env-file .env.test
          sleep 15
      - name: Install dependencies
        run: npm install
      - name: Run Component Tests
        run: npm run test:component
      - name: Run API Tests
        run: npm run test:api
      - name: Stop Containers
        run: docker compose down
